--------------------------------------------------------
--  File created - Tuesday-October-10-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PR_TAX_SETUP
--------------------------------------------------------

  CREATE TABLE "PR_TAX_SETUP" 
   (	"TAX_SETUP_KEY" NUMBER, 
	"TAX_CODE" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"TAX_DESC" VARCHAR2(128) COLLATE "USING_NLS_COMP", 
	"TAX_RANK" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"TAX_PERC" NUMBER, 
	"AMT_HIGHER" NUMBER, 
	"AMOUNT_FROM" NUMBER, 
	"AMOUNT_TO" NUMBER, 
	"RELIEF_PERC1" NUMBER, 
	"RELIEF_PERC2" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"STATE_CODE" VARCHAR2(20) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
REM INSERTING into PR_TAX_SETUP
SET DEFINE OFF;
REM INSERTING into PR_TAX_SETUP
SET DEFINE OFF;
Insert into PR_TAX_SETUP (TAX_SETUP_KEY,TAX_CODE,TAX_DESC,TAX_RANK,TAX_PERC,AMT_HIGHER,AMOUNT_FROM,AMOUNT_TO,RELIEF_PERC1,RELIEF_PERC2,STATE_CODE) values (700,'UK','Personal Allowance','1',0,null,0,12570,null,null,null);
Insert into PR_TAX_SETUP (TAX_SETUP_KEY,TAX_CODE,TAX_DESC,TAX_RANK,TAX_PERC,AMT_HIGHER,AMOUNT_FROM,AMOUNT_TO,RELIEF_PERC1,RELIEF_PERC2,STATE_CODE) values (701,'UK','Basic rate','2',0.2,null,12571,50270,null,null,null);
Insert into PR_TAX_SETUP (TAX_SETUP_KEY,TAX_CODE,TAX_DESC,TAX_RANK,TAX_PERC,AMT_HIGHER,AMOUNT_FROM,AMOUNT_TO,RELIEF_PERC1,RELIEF_PERC2,STATE_CODE) values (702,'UK','Higher rate','3',0.4,null,50271,125140,null,null,null);
Insert into PR_TAX_SETUP (TAX_SETUP_KEY,TAX_CODE,TAX_DESC,TAX_RANK,TAX_PERC,AMT_HIGHER,AMOUNT_FROM,AMOUNT_TO,RELIEF_PERC1,RELIEF_PERC2,STATE_CODE) values (703,'UK','Additional rate','4',0.45,null,125141,1000000000000,null,null,null);
Insert into PR_TAX_SETUP (TAX_SETUP_KEY,TAX_CODE,TAX_DESC,TAX_RANK,TAX_PERC,AMT_HIGHER,AMOUNT_FROM,AMOUNT_TO,RELIEF_PERC1,RELIEF_PERC2,STATE_CODE) values (704,'NG','First 200,000 or 1 % (Higher) +  20% income + Pension + Tax Reliefs','0',0,200000,0,0,0.01,'.2',null);
Insert into PR_TAX_SETUP (TAX_SETUP_KEY,TAX_CODE,TAX_DESC,TAX_RANK,TAX_PERC,AMT_HIGHER,AMOUNT_FROM,AMOUNT_TO,RELIEF_PERC1,RELIEF_PERC2,STATE_CODE) values (705,'NG','First 300,000','1',0.07,null,0,300000.99,null,null,null);
Insert into PR_TAX_SETUP (TAX_SETUP_KEY,TAX_CODE,TAX_DESC,TAX_RANK,TAX_PERC,AMT_HIGHER,AMOUNT_FROM,AMOUNT_TO,RELIEF_PERC1,RELIEF_PERC2,STATE_CODE) values (706,'NG','Next 300,000','2',0.11,null,300001,600000.99,null,null,null);
Insert into PR_TAX_SETUP (TAX_SETUP_KEY,TAX_CODE,TAX_DESC,TAX_RANK,TAX_PERC,AMT_HIGHER,AMOUNT_FROM,AMOUNT_TO,RELIEF_PERC1,RELIEF_PERC2,STATE_CODE) values (707,'NG','Next 500,000','3',0.15,null,600001,1100000.99,null,null,null);
Insert into PR_TAX_SETUP (TAX_SETUP_KEY,TAX_CODE,TAX_DESC,TAX_RANK,TAX_PERC,AMT_HIGHER,AMOUNT_FROM,AMOUNT_TO,RELIEF_PERC1,RELIEF_PERC2,STATE_CODE) values (708,'NG','Next 500,000','4',0.19,null,1100001,1600000.99,null,null,null);
Insert into PR_TAX_SETUP (TAX_SETUP_KEY,TAX_CODE,TAX_DESC,TAX_RANK,TAX_PERC,AMT_HIGHER,AMOUNT_FROM,AMOUNT_TO,RELIEF_PERC1,RELIEF_PERC2,STATE_CODE) values (709,'NG','Next 1,600,000','5',0.21,null,1600001,3200000.99,null,null,null);
Insert into PR_TAX_SETUP (TAX_SETUP_KEY,TAX_CODE,TAX_DESC,TAX_RANK,TAX_PERC,AMT_HIGHER,AMOUNT_FROM,AMOUNT_TO,RELIEF_PERC1,RELIEF_PERC2,STATE_CODE) values (710,'NG','Next 1,000,000,000,000','6',0.24,null,3200001,1000000000000,null,null,null);
Insert into PR_TAX_SETUP (TAX_SETUP_KEY,TAX_CODE,TAX_DESC,TAX_RANK,TAX_PERC,AMT_HIGHER,AMOUNT_FROM,AMOUNT_TO,RELIEF_PERC1,RELIEF_PERC2,STATE_CODE) values (711,'CA','Federal income tax 1','1',0.15,null,0,50197,null,null,null);
Insert into PR_TAX_SETUP (TAX_SETUP_KEY,TAX_CODE,TAX_DESC,TAX_RANK,TAX_PERC,AMT_HIGHER,AMOUNT_FROM,AMOUNT_TO,RELIEF_PERC1,RELIEF_PERC2,STATE_CODE) values (712,'CA','Federal income tax 2','2',0.205,null,50198,100392,null,null,null);
Insert into PR_TAX_SETUP (TAX_SETUP_KEY,TAX_CODE,TAX_DESC,TAX_RANK,TAX_PERC,AMT_HIGHER,AMOUNT_FROM,AMOUNT_TO,RELIEF_PERC1,RELIEF_PERC2,STATE_CODE) values (713,'CA','Federal income tax 3','3',0.26,null,100393,155625,null,null,null);
Insert into PR_TAX_SETUP (TAX_SETUP_KEY,TAX_CODE,TAX_DESC,TAX_RANK,TAX_PERC,AMT_HIGHER,AMOUNT_FROM,AMOUNT_TO,RELIEF_PERC1,RELIEF_PERC2,STATE_CODE) values (714,'CA','Federal income tax 4','4',0.29,null,155626,221708,null,null,null);
Insert into PR_TAX_SETUP (TAX_SETUP_KEY,TAX_CODE,TAX_DESC,TAX_RANK,TAX_PERC,AMT_HIGHER,AMOUNT_FROM,AMOUNT_TO,RELIEF_PERC1,RELIEF_PERC2,STATE_CODE) values (715,'CA','Federal income tax 5','5',0.33,null,221709,1000000000000,null,null,null);

--------------------------------------------------------
--  DDL for Index PR_TAX_SETUP_PK
--------------------------------------------------------
commit;
